version: '3.8'

services:
  ruby:
    image: ruby:3.3
    container_name: ruby_mcp
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: bash -c "bundle install && rails server -b 0.0.0.0"

  redmine:
    image: redmine:latest
    container_name: redmine
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: password
    ports:
      - "8080:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: redmine_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redmine
    volumes:
      - redmine_db_data:/var/lib/mysql

volumes:
  redmine_db_data: